name: ☑️任务单
description: 一些任务单，可以用来起草新版本规划等。
title: "☑️[TASK]"
labels: enhancement
type: Task
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > 为避免造成更多的麻烦，请在报告issue前，先检查是否有其他人已经报告过相同的问题。[检查是否存在重复](https://github.com/xystudiocode/pyclickmouse/issues)😊
      
      > [!IMPORTANT]
      > 我们不会在gitee上处理issue，请使用github发布。🙋‍♂️
- type: textarea
  attributes:
    label: 🧾新增的每个功能描述
    placeholder: |
      - 新功能1
      - 新功能2
      - 新功能3
      - 新功能...
    description: 🧾请详细描述你想要新增的功能。
  validations:
    required: true
- type: textarea
  attributes:
    label: ❓需要这些功能的原因
    placeholder: |
      解决了什么问题？
      改进了什么？
      其他原因...
    description: ❓为什么需要这个功能？
  validations:
    required: false
- type: textarea
  attributes:
    label: 📄实行步骤想法
    placeholder: |
      - 新功能1:
      - - 实行方案1:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 实行方案2:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 实行方案3:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 其他实行方案...
      - 新功能2:
      - - 实行方案1:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 实行方案2:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 实行方案3:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 其他实行方案...
      - 新功能3:
      - - 实行方案1:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 实行方案2:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 实行方案3:
      - - 1. 实行步骤1
      - - 2. 实行步骤2
      - - 3. 实行步骤3
      - - 4. 实行步骤...
      - - 其他实行方案...
      - 其他功能...
    description: ♻️可以提供多个新功能的多个实行方案，但请确保每个方案都能实行你的需求。
  validations:
    required: false
- type: textarea
  attributes:
    label: ➕其他相关信息
    description: ✉️你了解到的更多内容
    placeholder: |
      更多信息。
  validations:
    required: false